baseURL = "https://docs.qlarm.com/"
staticDir = ["static"]
languageCode = "en-us"
title = "Qlarm Documentation"
theme = "ace-documentation"
publishDir = "docs"
googleAnalytics = "UA-2760582-5"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
home = [ "HTML" ]