baseURL = "https://docs.qlarm.com/"
staticDir = ["static"]
languageCode = "en-us"
title = "QLARM Documentation"
theme="ace-documentation"
publishDir = "docs"
unsafe = true
[markup.goldmark.renderer]
  unsafe= true
